// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    VDarkModeSwitcher: typeof import('./src/components/VDarkModeSwitcher.vue')['default']
    VDatatable: typeof import('./src/components/VDatatable.vue')['default']
    VDatatableBody: typeof import('./src/components/VDatatableBody.vue')['default']
    VDatatableFooter: typeof import('./src/components/VDatatableFooter.vue')['default']
    VDatatableHeader: typeof import('./src/components/VDatatableHeader.vue')['default']
    VTableCards: typeof import('./src/components/VTableCards.vue')['default']
  }
}
