export const users = [
  {
    name: 'John Doe',
    avatar: 'https://i.pravatar.cc/300',
    email: 'john.doe@example.com',
    age: 35,
    activated: true,
    company: 'Apple',
  },
  {
    name: 'Jane Smith',
    avatar: 'https://i.pravatar.cc/301',
    email: 'jane.smith@example.com',
    age: 28,
    activated: true,
    company: 'Google',
  },
  {
    name: 'Bob Johnson',
    avatar: 'https://i.pravatar.cc/302',
    email: 'bob.johnson@example.com',
    age: 42,
    activated: false,
    company: 'Microsoft',
  },
  // Additional rows
  {
    name: 'Alice Williams',
    avatar: 'https://i.pravatar.cc/303',
    email: 'alice.williams@example.com',
    age: 29,
    activated: true,
    company: 'Facebook',
  },
  {
    name: 'Mike Thompson',
    avatar: 'https://i.pravatar.cc/304',
    email: 'mike.thompson@example.com',
    age: 41,
    activated: false,
    company: 'Amazon',
  },
  {
    name: 'Sarah Johnson',
    avatar: 'https://i.pravatar.cc/305',
    email: 'sarah.johnson@example.com',
    age: 33,
    activated: true,
    company: 'Netflix',
  },
  {
    name: 'David Smith',
    avatar: 'https://i.pravatar.cc/306',
    email: 'david.smith@example.com',
    age: 38,
    activated: false,
    company: 'Twitter',
  },
  {
    name: 'Jessica Williams',
    avatar: 'https://i.pravatar.cc/306',
    email: 'jessica.williams@example.com',
    age: 25,
    activated: true,
    company: 'Apple',
  },
  {
    name: 'James Thompson',
    avatar: 'https://i.pravatar.cc/307',
    email: 'james.thompson@example.com',
    age: 31,
    activated: false,
    company: 'Google',
  },
  {
    name: 'Emily Johnson',
    avatar: 'https://i.pravatar.cc/308',
    email: 'emily.johnson@example.com',
    age: 27,
    activated: true,
    company: 'Microsoft',
  },
  {
    name: 'William Smith',
    avatar: 'https://i.pravatar.cc/309',
    email: 'william.smith@example.com',
    age: 35,
    activated: false,
    company: 'Facebook',
  },
  {
    name: 'Ashley Williams',
    avatar: 'https://i.pravatar.cc/310',
    email: 'ashley.williams@example.com',
    age: 29,
    activated: true,
    company: 'Amazon',
  },
  {
    name: 'Michael Thompson',
    avatar: 'https://i.pravatar.cc/311',
    email: 'michael.@example.com',
    age: 41,
    activated: false,
    company: 'Netflix',
  },
  {
    name: 'Sarah Johnson',
    avatar: 'https://i.pravatar.cc/312',
    email: 'sera@exanoke@.com',
    age: 33,
    activated: true,
    company: 'Twitter',
  },
]
