export const users = [
  {
    name: 'John Doe',
    avatar: 'https://via.placeholder.com/150',
    email: 'john.doe@example.com',
    age: 35,
    activated: true,
  },
  {
    name: 'Jane Smith',
    avatar: 'https://via.placeholder.com/150',
    email: 'jane.smith@example.com',
    age: 28,
    activated: true,
  },
  {
    name: 'Bob Johnson',
    avatar: 'https://via.placeholder.com/150',
    email: 'bob.johnson@example.com',
    age: 42,
    activated: false,
  },
  {
    name: 'John Doe',
    avatar: 'https://via.placeholder.com/150',
    email: 'john.doe@example.com',
    age: 35,
    activated: true,
  },
  {
    name: 'Jane Smith',
    avatar: 'https://via.placeholder.com/150',
    email: 'jane.smith@example.com',
    age: 28,
    activated: true,
  },
  {
    name: 'Bob Johnson',
    avatar: 'https://via.placeholder.com/150',
    email: 'bob.johnson@example.com',
    age: 42,
    activated: false,
  },
  {
    name: 'John Doe',
    avatar: 'https://via.placeholder.com/150',
    email: 'john.doe@example.com',
    age: 35,
    activated: true,
  },
  {
    name: 'Jane Smith',
    avatar: 'https://via.placeholder.com/150',
    email: 'jane.smith@example.com',
    age: 28,
    activated: true,
  },
  {
    name: 'Bob Johnson',
    avatar: 'https://via.placeholder.com/150',
    email: 'bob.johnson@example.com',
    age: 42,
    activated: false,
  },
  {
    name: 'John Doe',
    avatar: 'https://via.placeholder.com/150',
    email: 'john.doe@example.com',
    age: 35,
    activated: true,
  },
  {
    name: 'Jane Smith',
    avatar: 'https://via.placeholder.com/150',
    email: 'jane.smith@example.com',
    age: 28,
    activated: true,
  },
  {
    name: 'Bob Johnson',
    avatar: 'https://via.placeholder.com/150',
    email: 'bob.johnson@example.com',
    age: 42,
    activated: false,
  },
  {
    name: 'John Doe',
    avatar: 'https://via.placeholder.com/150',
    email: 'john.doe@example.com',
    age: 35,
    activated: true,
  },
  {
    name: 'Jane Smith',
    avatar: 'https://via.placeholder.com/150',
    email: 'jane.smith@example.com',
    age: 28,
    activated: true,
  },
  {
    name: 'Bob Johnson',
    avatar: 'https://via.placeholder.com/150',
    email: 'bob.johnson@example.com',
    age: 42,
    activated: false,
  },
  {
    name: 'John Doe',
    avatar: 'https://via.placeholder.com/150',
    email: 'john.doe@example.com',
    age: 35,
    activated: true,
  },
  {
    name: 'Jane Smith',
    avatar: 'https://via.placeholder.com/150',
    email: 'jane.smith@example.com',
    age: 28,
    activated: true,
  },
  {
    name: 'Bob Johnson',
    avatar: 'https://via.placeholder.com/150',
    email: 'bob.johnson@example.com',
    age: 42,
    activated: false,
  },
]
